# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in calendar.gemspec
gemspec

gem "rake", "~> 13.0"

gem "standard", "~> 1.3"

gem "nokogiri"

gem "aws_lambda_ric"
